KNU-HAEDAL/Gongsikdang-FE

src/pages/register/ui/RegisterPage.jsx
src/pages/register/ui/RegisterPage.style.js
src/pages/register/ui/index.js

feat/회원가입 페이지 수정

---

package-lock.json
package.json
src/pages/login/ui/LoginPage.jsx
src/pages/login/ui/LoginPage.style.js
src/shared/theme/global/globalStyle.js
vite.config.js

feat: 로그인 페이지 수정

---

.github/workflows/ci.yml

deploy: ci 수정

---

.github/workflows/ci.yml
.prettierrc
src/app/routes/Routes.jsx
src/shared/components/index.js
src/shared/components/layout/header/Header.jsx
src/shared/components/layout/header/Header.style.js
src/shared/components/layout/header/index.js
src/shared/components/layout/index.js
src/shared/index.js
src/shared/styles/index.js
src/shared/styles/layout/Header.jsx
src/shared/styles/layout/Layout.jsx
src/shared/styles/layout/Layout.style.js
src/shared/styles/layout/index.js
src/shared/theme/global/globalStyle.js

header ui 구현 및 router 설정 수정
---
---
---
- close #10

issue #10 header 적용

---

package-lock.json
package.json
src/App.jsx
src/app/routes/Routes.jsx
src/pages/login/apis/index.js
src/pages/login/apis/loginAPI.api.js
src/pages/login/ui/LoginPage.jsx
src/pages/register/apis/duplicate-id.api.js
src/pages/register/apis/index.js
src/pages/register/apis/registerApi.api.js
src/pages/register/ui/RegisterPage.jsx
src/pages/register/ui/RegisterPage.style.js
src/pages/select-corner/apis/index.js
src/pages/select-corner/apis/menuList.api.js
src/pages/select-corner/hooks/useGetMenuList.js
src/pages/select-corner/ui/SelectCornerPage.jsx
src/pages/select-corner/ui/SelectCornerPage.style.js
src/shared/components/index.js
src/shared/components/layout/header/Header.style.js
src/shared/components/spinner/LoadingView.jsx
src/shared/components/spinner/index.js
src/shared/instance/Instance.js
src/shared/instance/index.js
src/shared/instance/query-instance.js
src/shared/styles/layout/Layout.style.js
src/shared/theme/global/globalStyle.js

- 로그인 페이지 기능 수정
- 회원가입 페이지 기능 수정
- 전체 heigth 수정
- 컴포넌트 내부 스크롤 추가 및 스크롤 숨김 처리
- header에 토큰 담기 기능 추가
---
현재 토큰은 session storage에 저장되며, token으로 꺼내서 사용할 수 있습니다.
---
x
---
- closes #26

issue#26 로그인, 회원가입 페이지 기능 수정

---

src/pages/login/ui/LoginPage.jsx

localStorate, jwtToken 변경

---

src/pages/corner-A/ui/CornerAPage.jsx
src/pages/corner-A/ui/CornerAPage.style.js
src/pages/corner-B/ui/CornerBPage.jsx
src/pages/corner-B/ui/CornerBPage.style.js
src/pages/corner-C/ui/CornerCPage.jsx
src/pages/corner-C/ui/CornerCPage.style.js
src/pages/corner-D/ui/CornerDPage.jsx
src/pages/corner-D/ui/CornerDPage.style.js

8 각 코너별 음식 페이지 UI 제작

---

src/pages/select-corner/ui/SelectCornerPage.jsx

feat(selectcornerpage): fetchInstance 사용해서 api연동 개선

---

src/pages/login/ui/LoginPage.jsx

feat(login): sessionstorage, token 원상복구

---

src/pages/corner-A/apis/cornerA.api.js
src/pages/corner-A/ui/CornerAPage.jsx
src/pages/corner-B/apis/cornerB.api.js
src/pages/corner-B/ui/CornerBPage.jsx
src/pages/corner-C/apis/cornerC.api.js
src/pages/corner-C/ui/CornerCPage.jsx
src/pages/corner-D/apis/cornerD.api.js
src/pages/corner-D/ui/CornerDPage.jsx

각 코너별 apis폴더에 fetchinstance 파일 추가 및 api 연동 코드 개선
---
---
---

feat(corner): fetchinstance 사용해 api 연동 개선

---

src/pages/review-food/ui/ReviewFoodPage.jsx
src/pages/review-food/ui/ReviewFoodPage.style.js

배경중첩 문제 해결을 위해 background부분 삭제
---
---
---

feat(reviewfoodpage): 배경 중첩 문제 해결

---

src/pages/payment/ui/PaymentPage.jsx
src/pages/payment/ui/PaymentPage.style.js

feat(payment): 페이지 맞춤

---

src/pages/payment/ui/PaymentPage.jsx
src/pages/payment/ui/PaymentPage.style.js

feat(payment):페이지레이아웃 수정

---

src/pages/mypage/apis/index.js
src/pages/mypage/apis/name.api.js
src/pages/mypage/components/my-info/MyInfo.jsx
src/pages/mypage/components/purchases-list/PurchasesList.jsx
src/pages/mypage/hooks/index.js
src/pages/mypage/hooks/useGetName.js
src/pages/point/ui/PointPage.jsx
src/pages/point/ui/PointPage.style.js
src/shared/components/spinner/Spinner.jsx
src/shared/components/spinner/index.js

- 마이페이지 - 내 이름 불러오기 기능 수정
- spinner 컴포넌트 구현
- 포인트 충전 페이지 수정
- mock data 제거 및 실제 response data 적용
---
눈에 보이는 버그들은 일단 수정 완료했습니다.
---
마이페이지 구매 리스트 버튼 관련 기능들은 새로 수정해야겠네요.
---

issue#51 - 마이페이지 수정

---

src/pages/corner-A/ui/CornerAPage.jsx
src/pages/corner-A/ui/CornerAPage.style.js
src/pages/corner-B/ui/CornerBPage.jsx
src/pages/corner-B/ui/CornerBPage.style.js
src/pages/corner-C/ui/CornerCPage.jsx
src/pages/corner-C/ui/CornerCPage.style.js
src/pages/corner-D/ui/CornerDPage.jsx
src/pages/corner-D/ui/CornerDPage.style.js

장바구니 글자 간격 맞춤(가장 긴 메뉴 기준)
가격계산 오류문제 해결
---
---
---

fix(cornerpage): 장바구니 글자 위치 조정

---

src/pages/review-food/apis/reviewfood.api.js
src/pages/review-food/ui/ReviewFoodPage.jsx
src/pages/review-food/ui/ReviewFoodPage.style.js

리뷰 내용 api연동
별점순으로 정렬기능 추가
왼쪽 치우침 문제 해결
---
---
---

feat(reviewfoodpage): api연동, 정렬기능 추가

---

src/pages/review-food/ui/ReviewFoodPage.jsx
src/pages/review-food/ui/ReviewFoodPage.style.js

메뉴별로 해당 리뷰페이지로 이동하도록 수정
---
---
---

Feat/issue #44

---

src/app/routes/Routes.jsx
src/pages/corner-A/ui/CornerAPage.jsx
src/pages/corner-B/ui/CornerBPage.jsx
src/pages/corner-C/ui/CornerCPage.jsx
src/pages/corner-D/ui/CornerDPage.jsx
src/pages/review-food/apis/reviewfood.api.js
src/pages/review-food/ui/ReviewFoodPage.jsx
src/pages/review-food/ui/ReviewFoodPage.style.js

코너 페이지에서 주소 변경(리뷰보기 눌렀을때)
라우트에 foodid 주소 추가
---
---
---

feat(reviewfoodpage): 메뉴별 리뷰페이지 이동 api연동 구현

---

src/pages/payment/apis/point.api.js
src/pages/payment/ui/PaymentPage.jsx

결제페이지 포인트 API연동, 포인트 사용 및 결제 금액 수정 
---
---

feat(pointAPI): 포인트 API 연동

---

src/pages/payment/apis/purchases.api.js
src/pages/payment/apis/reduce.api.js
src/pages/payment/ui/PaymentPage.jsx

refactor(payment): 결제 및 재고감소 API 연동 ( 수정)

---

src/pages/payment/ui/PaymentPage.style.js

style(paymentPage): 결제 UI 수정

---

src/pages/review-write/apis/reviewwritepage.api.js
src/pages/review-write/ui/ReviewWritePage.jsx
src/pages/review-write/ui/ReviewWritePage.style.js

feat(reviewwritepage): 리뷰 작성 및 구매한 음식 목록 조회 API 추가(진행중)

---

src/pages/corner-A/ui/CornerAPage.jsx

a페이지 리뷰페이지 이동 주소 변경
---
---
---

feat(cornerAPage): 리뷰보기 버튼에 foodId 추가하여 상세 리뷰 페이지로 이동

---

src/pages/corner-A/ui/CornerAPage.jsx
src/pages/review-food/apis/reviewfood.api.js
src/pages/review-food/ui/ReviewFoodPage.jsx
src/pages/select-corner/ui/SelectCornerPage.style.js

feat(reviewfood): 리뷰 목록에서 음식 이름을 올바르게 표시, 리뷰를 음식별로 그룹화

---

src/pages/corner-A/ui/CornerAPage.jsx
src/pages/corner-B/ui/CornerBPage.jsx
src/pages/corner-C/ui/CornerCPage.jsx
src/pages/corner-D/ui/CornerDPage.jsx

feat(images): 메뉴 이미지 파일 경로 수정

---

src/pages/review-food/ui/ReviewFoodPage.jsx
src/pages/review-food/ui/ReviewFoodPage.style.js

feat(review): 리뷰가 없을 때 메시지 표시 및 코드 정리

---

src/pages/barcode/ui/BarcodePage.jsx
src/pages/mypage/apis/purchases-list.api.js
src/pages/mypage/components/purchases-list/PurchasesList.jsx
src/pages/mypage/components/purchases-list/PurchasesList.style.js
src/pages/payment/apis/purchases.api.js
src/pages/payment/ui/PaymentPage.jsx

feat(barcode, payment, mypage): 구매 내역API

---

src/pages/mypage/components/purchases-list/PurchasesList.jsx

feat(purchasesList): 구매 확정 및 리뷰 작성 기능 추가

---

package-lock.json
package.json
src/pages/barcode/ui/BarcodePage.jsx
src/pages/barcode/ui/BarcodePage.style.js
src/pages/mypage/components/purchases-list/PurchasesList.jsx

---
마이페이지 구매내역 파트 덮어쓰기
---
---

feat(barcode, mypage): QR 코드 기능 추가 및 구매 확정 로직 개선

---

src/pages/mypage/components/my-point/MyPoint.jsx
src/pages/payment/ui/PaymentPage.jsx

feat(mypage, payment): 포인트 차감

---

src/pages/mypage/components/purchases-list/PurchasesList.jsx
src/pages/review-food/apis/reviewfood.api.js
src/pages/review-write/apis/reviewwritepage.api.js
src/pages/review-write/ui/ReviewWritePage.jsx

리뷰 작성페이지 메뉴 이름 추가
일부 콘솔 추가
---
---
---

feat(reviewwrite): 리뷰작성페이지 메뉴이름 추가

---

src/pages/mypage/components/my-point/MyPoint.jsx
src/pages/payment/apis/point.api.js
src/pages/payment/apis/purchases.api.js
src/pages/payment/ui/PaymentPage.jsx
src/pages/point/apis/point-charge.api.js
src/pages/point/ui/PointPage.jsx

feat(PointPage,PaymentPage) : 포인트 사용, 포인트 증감 반영

---

src/pages/payment/ui/PaymentPage.jsx
src/shared/instance/Instance.js

fix(,Instance):axios 타임아웃 증가

---

src/pages/review-food/apis/reviewfood.api.js
src/pages/review-food/ui/ReviewFoodPage.jsx
src/pages/review-write/apis/reviewwritepage.api.js
src/pages/review-write/ui/ReviewWritePage.jsx

refactor(ReviewFoodPage, ReviewWritePage): 리뷰 데이터 처리 및 API 호출 개선

---

index.html

[배포] pwa 적용

---

src/pages/register/ui/RegisterPage.jsx

feat(RegisterPage): 아이디, 닉네임,  유효성 검사

---

src/pages/payment/ui/PaymentPage.jsx
src/pages/point/ui/PointPage.jsx

feat(PaymentPage, PointPage): 결제 데이터에 리다이렉트 URL 추가

---

src/pages/mypage/components/purchases-list/PurchasesList.jsx
src/pages/review-write/ui/ReviewWritePage.jsx

feat(PurchasesList, ReviewWritePage): 구매확정 및 리뷰완료 상태 관리 추가

---

src/pages/payment/ui/PaymentPage.jsx

feat: 결제 페이지 이동 변경

---

src/shared/theme/global/globalStyle.js

!Hotfix: 폰트 수정사항 반영
